### ISSUE TITLE
预约历史和预约管理模块的开发建议

### ISSUE THREAD

**Issue by mzz2017** [mzz2017/pcbsystem_web#3]
### 1. 预约历史和预约管理模块的开发建议
建议合并在一起叫做预约管理，下面放一个Tabbar，分为以下几个模块
#### 1.1 正在进行与正在申请（我的行程）
对正在进行的预约进行查看，对还未通过的预约进行查看和取消，十条十条显示，拉到最下再次渲染，仿照知乎。
#### 1.2 预约历史
对已经过了终约时间的预约进行查看。

**Comment by ooobsidian** [comment]
明白
